using System;
using System.Linq;
using UnityEngine;
using UnityEngine.AI;

/// <summary>
/// NavMeshSurface helper class that is used to attach the NavMeshSurface component to
/// the appropriate spatial mesh generated by ARMeshManager and update the NavMesh at runtime
/// </summary>
public class NavMeshBuilder : Singleton<NavMeshBuilder>
{
    [SerializeField] private float _navMeshUpdateFrequency = 15.0f;
    [SerializeField] private bool _isVisualizeWalkableArea = false;

    private NavMeshSurface _surface;
    private MeshFilter _meshFilter;

    protected override void Awake()
    {
        base.Awake();
        _meshFilter = GetComponent<MeshFilter>();
    }

    private void Start()
    {
        StateManager.OnAfterStateChanged += StateChanged;
        ReorganizeSpatialMesh();
    }

    private void OnDestroy()
    {
        StateManager.OnAfterStateChanged -= StateChanged;
    }

    private void StateChanged(State newState)
    {
        switch (newState)  // turn off navmesh builder when doing UIA and turn on for the other tasks
        {
            case State.Indoor:
                CancelInvoke();
                break;
            default:
                InvokeRepeating(nameof(BuildNavMesh), 0.0f, _navMeshUpdateFrequency);
                break;
        }
    }

    /// <summary>
    /// Wrapper method that controls how to build the NavMesh
    /// </summary>
    public void BuildNavMesh()
    {
        // directly calls BuildNavMesh for now
        _surface.BuildNavMesh();
        if (_isVisualizeWalkableArea)
        {
            NavMeshTriangulation _meshData = NavMesh.CalculateTriangulation();
            Mesh mesh = new Mesh();
            mesh.vertices = _meshData.vertices;
            mesh.triangles = _meshData.indices;
            _meshFilter.mesh = mesh;
        }
        else
        {
            _meshFilter.mesh = null;
        }
    }

    public void UpdateNavMeshVisualize(bool isToDisplay)
    {
        _isVisualizeWalkableArea = isToDisplay;
    }

    /// <summary>
    /// Reorganize spatial mesh gameobjects and add NavMeshSurface component
    /// </summary>
    private void ReorganizeSpatialMesh()
    {
        GameObject spatialMesh = GameObject.Find("Trackables");
        spatialMesh.name = "spatialMesh";
        GameObject spatialMeshChild = GameObject.Find("Trackables");
        spatialMeshChild.name = "spatialMeshChild";
        spatialMeshChild.transform.SetParent(spatialMesh.transform);
        _surface = spatialMesh.AddComponent<NavMeshSurface>();
        _surface.useGeometry = NavMeshCollectGeometry.PhysicsColliders;
        _surface.collectObjects = CollectObjects.Children;
        spatialMesh.tag = "SpatialMesh";
    }
}