using System;
using UnityEngine;
using UnityEngine.AI;

/// <summary>
/// NavMeshSurface helper class that is used to attach the NavMeshSurface component to
/// the appropriate spatial mesh generated by ARMeshManager and update the NavMesh at runtime
/// </summary>
public class NavMeshBuilder : Singleton<NavMeshBuilder>
{
    [SerializeField] private float _navMeshUpdateFrequency = 15.0f;

    private NavMeshSurface _surface;

    private void Start()
    {
        StateManager.OnAfterStateChanged += StateChanged;
        ReorganizeSpatialMesh();
    }

    private void OnDestroy()
    {
        StateManager.OnAfterStateChanged -= StateChanged;
    }

    private void StateChanged(State newState)
    {
        switch (newState)  // turn off navmesh builder when doing UIA and turn on for the other tasks
        {
            case State.Indoor:
                CancelInvoke();
                break;
            case State.Outdoor:
                InvokeRepeating("BuildNavMesh", 0.0f, _navMeshUpdateFrequency);
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(newState), newState, null);
        }
    }

    /// <summary>
    /// Wrapper method that controls how to build the NavMesh
    /// </summary>
    private void BuildNavMesh()
    {
        // directly calls BuildNavMesh for now
        _surface.BuildNavMesh();
    }

    /// <summary>
    /// Reorganize spatial mesh gameobjects and add NavMeshSurface component
    /// </summary>
    private void ReorganizeSpatialMesh()
    {
        GameObject spatialMesh = GameObject.Find("Trackables");
        spatialMesh.name = "spatialMesh";
        GameObject spatialMeshChild = GameObject.Find("Trackables");
        spatialMeshChild.name = "spatialMeshChild";
        spatialMeshChild.transform.SetParent(spatialMesh.transform);
        _surface = spatialMesh.AddComponent<NavMeshSurface>();
        _surface.useGeometry = NavMeshCollectGeometry.PhysicsColliders;
        _surface.collectObjects = CollectObjects.Children;
    }
}